services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Utilise tous les GPU disponibles
              capabilities: [ gpu ]
    volumes:
      - ollama_storage:/root/.ollama
#    restart: unless-stopped
    restart: no

volumes:
  ollama_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/ollama/storage
